# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xX5gCc5r-h81URnYK-KjwDqlAFcgcWms
"""

from google.colab import files
uploaded=files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import r2_score, mean_absolute_error

# --- 1. Data Loading and Cleaning (Simplified) ---
# This section loads your data and cleans it up so the model can understand it.
# IMPORTANT: This script is now configured to use 'quikr_car.csv'.
# Make sure the CSV file is in the same directory as this script.
try:
    car = pd.read_csv('quikr_car.csv')
    print("Data loaded successfully.")
except FileNotFoundError:
    print("Error: The file 'quikr_car.csv' was not found.")
    print("Please make sure your CSV file is in the same directory and the filename is correct.")
    # Creating a sample DataFrame for demonstration purposes if the file is not found.
    data = {
        'name': ['Maruti Suzuki Swift', 'Mahindra XUV500 W8', 'Hyundai i20'],
        'company': ['Maruti', 'Mahindra', 'Hyundai'],
        'year': ['2015', '2019', '2017'],
        'Price': ['3,50,000', '12,00,000', '4,50,000'],
        'kms_driven': ['50000 kms', '25,000 km', '35000 kms'],
        'fuel_type': ['Petrol', 'Diesel', 'Petrol'],
    }
    car = pd.DataFrame(data)
    print("Using a sample DataFrame for demonstration.")

# Filter out rows with non-numeric years and "Ask For Price" entries.
car = car[car['year'].str.isnumeric()]
car['year'] = car['year'].astype(int)
car = car[car['Price'] != 'Ask For Price']

# Clean the 'Price' column by removing commas and converting to a number.
car['Price'] = car['Price'].str.replace(',', '').astype(int)

# Clean the 'kms_driven' column by removing ' kms' or ' km' and commas.
car['kms_driven'] = car['kms_driven'].str.split().str.get(0).str.replace(',', '')
car = car[car['kms_driven'].str.isnumeric()] # Remove any non-numeric entries
car['kms_driven'] = car['kms_driven'].astype(int)

# Remove rows with missing fuel type.
car = car[~car['fuel_type'].isna()]

# Simplify the 'name' column by keeping only the first three words.
car['name'] = car['name'].str.split().str.slice(stop=3).str.join(' ')

# Reset the index after cleaning the data.
car = car.reset_index(drop=True)

# Remove prices that seem unusually high to handle outliers.
car = car[car['Price'] < 6000000]

print("\n--- First 5 rows of cleaned data ---")
print(car.head())


# --- 2. Exploratory Data Analysis (EDA) and Visual Insights ---
# This part creates graphs to help you understand your data better.
print("\n--- Generating Visual Insights ---")

sns.set_style("whitegrid")
plt.figure(figsize=(18, 16))

# Subplot 1: Price distribution by Company (Box Plot)
plt.subplot(3, 2, 1)
ax = sns.boxplot(x='company', y='Price', data=car)
ax.set_xticklabels(ax.get_xticklabels(), rotation=40, ha='right')
plt.title('Price Distribution by Company', fontsize=14)
plt.xlabel('Company', fontsize=12)
plt.ylabel('Price ($)', fontsize=12)

# Subplot 2: Average Price by Fuel Type (Bar Chart)
plt.subplot(3, 2, 2)
sns.barplot(x='fuel_type', y='Price', data=car.groupby('fuel_type')['Price'].mean().reset_index())
plt.title('Average Price by Fuel Type', fontsize=14)
plt.xlabel('Fuel Type', fontsize=12)
plt.ylabel('Average Price ($)', fontsize=12)

# Subplot 3: Price vs. Kilometers Driven (Scatter Plot)
plt.subplot(3, 2, 3)
sns.scatterplot(x='kms_driven', y='Price', data=car)
plt.title('Price vs. Kilometers Driven', fontsize=14)
plt.xlabel('Kilometers Driven', fontsize=12)
plt.ylabel('Price ($)', fontsize=12)

# Subplot 4: Price vs. Year (Contour Plot - a density plot alternative)
plt.subplot(3, 2, 4)
sns.kdeplot(x='year', y='Price', data=car, fill=True, cmap='viridis')
plt.title('Price vs. Year (Density)', fontsize=14)
plt.xlabel('Year', fontsize=12)
plt.ylabel('Price ($)', fontsize=12)

# Subplot 5: Price vs. Kilometers Driven by Fuel Type (Scatter Plot)
plt.subplot(3, 2, 5)
sns.scatterplot(x='kms_driven', y='Price', hue='fuel_type', data=car)
plt.title('Price vs. Kms by Fuel Type', fontsize=14)
plt.xlabel('Kilometers Driven', fontsize=12)
plt.ylabel('Price ($)', fontsize=12)

plt.tight_layout()
plt.savefig('unique_visual_insights.png')
print("Visual insights saved as 'unique_visual_insights.png'.")
plt.show()

# Additional Plot: Correlation Heatmap
plt.figure(figsize=(8, 6))
numeric_cols = car.select_dtypes(include=np.number)
sns.heatmap(numeric_cols.corr(), annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Heatmap of Numerical Features', fontsize=14)
plt.savefig('correlation_heatmap.png')
print("Correlation heatmap saved as 'correlation_heatmap.png'.")
plt.show()


# --- 3. Model Building and Training (Simplified) ---
# Here, we prepare the data and train a simple model.
print("\n--- Building and Training Model ---")

# Separate the data into features (X) and the target variable (y).
X = car[['name', 'company', 'year', 'kms_driven', 'fuel_type']]
y = car['Price']

# Split the data into training and testing sets.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Select the categorical columns for one-hot encoding.
categorical_cols = ['name', 'company', 'fuel_type']

# Create and fit the OneHotEncoder on the training data.
ohe = OneHotEncoder(handle_unknown='ignore')
ohe.fit(X_train[categorical_cols])

# Transform both training and testing data.
X_train_ohe = ohe.transform(X_train[categorical_cols])
X_test_ohe = ohe.transform(X_test[categorical_cols])

# Convert the one-hot encoded data to a DataFrame for easier handling.
X_train_ohe_df = pd.DataFrame(X_train_ohe.toarray(), columns=ohe.get_feature_names_out(categorical_cols), index=X_train.index)
X_test_ohe_df = pd.DataFrame(X_test_ohe.toarray(), columns=ohe.get_feature_names_out(categorical_cols), index=X_test.index)

# Combine the numerical and one-hot encoded features.
X_train_processed = pd.concat([X_train.drop(categorical_cols, axis=1), X_train_ohe_df], axis=1)
X_test_processed = pd.concat([X_test.drop(categorical_cols, axis=1), X_test_ohe_df], axis=1)

# Now, we train a single model.
model = LinearRegression()

# Fit the model to our training data.
model.fit(X_train_processed, y_train)

# Make predictions on the test data.
y_pred = model.predict(X_test_processed)

# --- 4. Evaluation and Comparison ---
# This section shows you how well the model performed.
print("\n--- Model Performance ---")
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
print(f"Linear Regression R-squared: {r2:.4f}")
print(f"Linear Regression MAE: ${mae:.2f}\n")


# --- 5. Visualization of Predictions vs. Actual values ---
# This creates a graph to visually compare the model's predictions.
print("\n--- Generating Model Prediction Plot ---")

plt.figure(figsize=(8, 6))

# Plotting the predictions against the actual values
sns.scatterplot(x=y_test, y=y_pred, label='Predictions', color='purple', alpha=0.7)

# Plotting the ideal line (y=x)
sns.lineplot(x=y_test, y=y_test, color='red', linestyle='--', label='Ideal Line')

plt.title('Linear Regression Predictions vs. Actual', fontsize=14)
plt.xlabel('Actual Price ($)', fontsize=12)
plt.ylabel('Predicted Price ($)', fontsize=12)
plt.legend()

plt.tight_layout()
plt.savefig('unique_model_predictions.png')
print("Model prediction comparison saved as 'unique_model_predictions.png'.")
plt.show()

print("\nScript execution complete.")
print("Please review the generated plots: 'unique_visual_insights.png', 'correlation_heatmap.png', and 'unique_model_predictions.png'.")